package cliutils

import (
	"whatsrook/cli/utils/meta"
)

// MetaAiResult wraps text and media generated by Meta AI.
type MetaAiResult = meta.MetaAiResult

// CSAITrait defines a personality trait for customized Meta AI persona.
type CSAITrait = meta.CSAITrait

var (
	// MetaAiBotJID is the official Meta AI bot JID on WhatsApp.
	MetaAiBotJID = meta.MetaAiBotJID

	// IsDummyPlaceholderText checks if text contains only placeholder indicators.
	IsDummyPlaceholderText = meta.IsDummyPlaceholderText

	// ExtractMetaAiText extracts textual content from Meta AI response messages.
	ExtractMetaAiText = meta.ExtractMetaAiText

	// ExtractMetaAiGeneratedImage extracts media URL, mime type, and caption.
	ExtractMetaAiGeneratedImage = meta.ExtractMetaAiGeneratedImage

	// ExtractMetaAiGeneratedMedia extracts generated media from response messages.
	ExtractMetaAiGeneratedMedia = meta.ExtractMetaAiGeneratedMedia

	// ExecuteMetaAiQuery sends an execution query to Meta AI on WhatsApp.
	ExecuteMetaAiQuery = meta.ExecuteMetaAiQuery

	// QueryMetaAi queues and executes a request to Meta AI.
	QueryMetaAi = meta.QueryMetaAi

	// DefaultCSAITraits contains preset AI personality personas.
	DefaultCSAITraits = meta.DefaultCSAITraits
)
